---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: user-db
  namespace: user
spec:
  instances: 3

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: 18

  postgresql:
    parameters:
      # See https://cloudnative-pg.io/docs/1.28/postgresql_conf for more info
      # on why we set the following parameters.
      wal_level: 'replica'
      auto_explain.log_min_duration: "10s"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  storage:
    size: 2Gi