// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Room struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type RoomMember struct {
	RoomID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
}
