// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: room/v1/room.proto

package roomv1

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RoomServiceName is the fully-qualified name of the RoomService service.
	RoomServiceName = "room.v1.RoomService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RoomServiceCreateRoomProcedure is the fully-qualified name of the RoomService's CreateRoom RPC.
	RoomServiceCreateRoomProcedure = "/room.v1.RoomService/CreateRoom"
)

// RoomServiceClient is a client for the room.v1.RoomService service.
type RoomServiceClient interface {
	CreateRoom(context.Context, *connect.Request[CreateRoomRequest]) (*connect.Response[CreateRoomResponse], error)
}

// NewRoomServiceClient constructs a client for the room.v1.RoomService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoomServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RoomServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	roomServiceMethods := File_room_v1_room_proto.Services().ByName("RoomService").Methods()
	return &roomServiceClient{
		createRoom: connect.NewClient[CreateRoomRequest, CreateRoomResponse](
			httpClient,
			baseURL+RoomServiceCreateRoomProcedure,
			connect.WithSchema(roomServiceMethods.ByName("CreateRoom")),
			connect.WithClientOptions(opts...),
		),
	}
}

// roomServiceClient implements RoomServiceClient.
type roomServiceClient struct {
	createRoom *connect.Client[CreateRoomRequest, CreateRoomResponse]
}

// CreateRoom calls room.v1.RoomService.CreateRoom.
func (c *roomServiceClient) CreateRoom(ctx context.Context, req *connect.Request[CreateRoomRequest]) (*connect.Response[CreateRoomResponse], error) {
	return c.createRoom.CallUnary(ctx, req)
}

// RoomServiceHandler is an implementation of the room.v1.RoomService service.
type RoomServiceHandler interface {
	CreateRoom(context.Context, *connect.Request[CreateRoomRequest]) (*connect.Response[CreateRoomResponse], error)
}

// NewRoomServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoomServiceHandler(svc RoomServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	roomServiceMethods := File_room_v1_room_proto.Services().ByName("RoomService").Methods()
	roomServiceCreateRoomHandler := connect.NewUnaryHandler(
		RoomServiceCreateRoomProcedure,
		svc.CreateRoom,
		connect.WithSchema(roomServiceMethods.ByName("CreateRoom")),
		connect.WithHandlerOptions(opts...),
	)
	return "/room.v1.RoomService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoomServiceCreateRoomProcedure:
			roomServiceCreateRoomHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoomServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoomServiceHandler struct{}

func (UnimplementedRoomServiceHandler) CreateRoom(context.Context, *connect.Request[CreateRoomRequest]) (*connect.Response[CreateRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("room.v1.RoomService.CreateRoom is not implemented"))
}
